// server.js
const fs = require('fs');
const https = require('https');
const express = require('express');
const path = require('path');

const app = express();

// Serve static files (index.html, js, css)
app.use(express.static(__dirname));

// Load SSL certs generated by mkcert
const options = {
  key: fs.readFileSync(path.join(__dirname, 'localhost+2-key.pem')),
  cert: fs.readFileSync(path.join(__dirname, 'localhost+2.pem'))
};

const PORT = 3000;

https.createServer(options, app).listen(PORT, () => {
  console.log(`✅ HTTPS server running at https://localhost:${PORT}`);
});

app.get('/callback', (req, res) => {
  // Always serve your index.html for the callback
  res.sendFile(path.join(__dirname, 'index.html'));
});
